### ISSUE TITLE
Support locally installed version of Solium.

### ISSUE THREAD

**Issue by MicahZoltu** [beaugunderson/vscode-solidity#2]
It would be nice if I have Solium NPM package installed in `${workspaceRoot}/node_modules` if that version were used rather than whatever is bundled with the extension.  The TypeScript extension goes one step further and prompts the user to choose which they want to use for the session if it detects a conflict, this would be very cool, but probably overkill.

**Comment by beaugunderson** [comment]
added in 2.0.0
